# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('a_slug', models.SlugField(help_text='Just type asdf or whatever. This will auto generate upon save', unique=True)),
                ('header_image', models.ImageField(upload_to='adventure_images/')),
                ('short_description', models.CharField(max_length=500)),
                ('what_you_get', models.TextField(default='you get a super awesome trip')),
                ('day_layout', models.TextField(default='randominput')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('inventory', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Price with decimals. EX 10.00 is $10.00', max_digits=29)),
                ('stripe_price', models.IntegerField(default=0, help_text='Price without decimals. EX 1059 is $10.59')),
                ('single_payment', models.DecimalField(decimal_places=2, default=0, help_text='One number including cents. EX 1000 is $10.00', max_digits=29)),
                ('random_addition', models.IntegerField(default=1)),
            ],
        ),
    ]
