# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0002_adventure_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='sale_price',
            field=models.IntegerField(default=1000),
        ),
    ]
