# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 19:02
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0004_auto_20161013_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='unique_title',
        ),
        migrations.AddField(
            model_name='adventure',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='Something', unique_with=['title', 'start_date']),
        ),
    ]
