# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0005_auto_20161015_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='slug',
        ),
    ]
