# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0006_remove_adventure_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 10, 15, 21, 15, 53, 793337, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
