# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0007_adventure_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='end_date',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='start_date',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
