# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 23:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0008_auto_20161015_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adventure',
            old_name='slug',
            new_name='a_slug',
        ),
    ]
