# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 02:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0009_auto_20161015_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='header_image',
            field=models.ImageField(default=datetime.datetime(2016, 10, 18, 2, 42, 47, 74926, tzinfo=utc), upload_to='adventure_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adventure',
            name='a_slug',
            field=models.SlugField(help_text='Just type asdf or whatever. This will auto generate upon save', unique=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='price',
            field=models.IntegerField(default=1000, help_text='One number including cents. EX 1000 is $10.00'),
        ),
    ]
