# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0010_auto_20161017_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='on_sale',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='adventure',
            name='day_layout',
            field=models.TextField(default='randominput'),
        ),
        migrations.AddField(
            model_name='adventure',
            name='single_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='price',
            field=models.IntegerField(default=0, help_text='One number including cents. EX 1000 is $10.00'),
        ),
    ]
