# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0011_auto_20161018_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One number including cents. EX 1000 is $10.00', max_digits=7),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='single_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One number including cents. EX 1000 is $10.00', max_digits=7),
        ),
    ]
