# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0012_auto_20161021_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One number including cents. EX 1000 is $10.00', max_digits=29),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='single_payment',
            field=models.DecimalField(decimal_places=2, default=0, help_text='One number including cents. EX 1000 is $10.00', max_digits=29),
        ),
    ]
