# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0013_auto_20161024_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='stripe_price',
            field=models.IntegerField(default=0, help_text='Price without decimals. EX 1059 is $10.59'),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price with decimals. EX 10.00 is $10.00', max_digits=29),
        ),
    ]
