# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0014_auto_20161024_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='what_you_get',
            field=models.TextField(default='you get a super awesome trip'),
        ),
    ]
