# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiing', '0015_adventure_what_you_get'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
